FROM python:3.7
#ADD . /code

# Use subdirectory as working directory
WORKDIR /app

# Install extra requirements for actions code, if necessary (uncomment next line)
#RUN pip3 install -r requirements.txt
USER 1001
CMD [ "python", "request.py" ]
