FROM rasa/rasa:1.9.7

 # The Rasa SDK image runs as non-root user by default. Hence, you have to switch
 # back to the `root` user if you want to install additional dependencies


# Switch back to a non-root user
USER 1001
CMD [ "run", "actions" ]
